# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\interfaceVisual\janelaExecucao.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowExecucao(object):
    def setupUi(self, MainWindowExecucao):
        MainWindowExecucao.setObjectName("MainWindowExecucao")
        MainWindowExecucao.resize(800, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindowExecucao.sizePolicy().hasHeightForWidth())
        MainWindowExecucao.setSizePolicy(sizePolicy)
        MainWindowExecucao.setMinimumSize(QtCore.QSize(800, 400))
        MainWindowExecucao.setMaximumSize(QtCore.QSize(800, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindowExecucao)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameSecaoProgresso = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frameSecaoProgresso.setFont(font)
        self.frameSecaoProgresso.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameSecaoProgresso.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSecaoProgresso.setObjectName("frameSecaoProgresso")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frameSecaoProgresso)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.progressBarExecucao = QtWidgets.QProgressBar(self.frameSecaoProgresso)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBarExecucao.sizePolicy().hasHeightForWidth())
        self.progressBarExecucao.setSizePolicy(sizePolicy)
        self.progressBarExecucao.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBarExecucao.setProperty("value", 0)
        self.progressBarExecucao.setTextVisible(True)
        self.progressBarExecucao.setInvertedAppearance(False)
        self.progressBarExecucao.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBarExecucao.setObjectName("progressBarExecucao")
        self.verticalLayout_3.addWidget(self.progressBarExecucao)
        self.labelDescricaoPassos = QtWidgets.QLabel(self.frameSecaoProgresso)
        self.labelDescricaoPassos.setMinimumSize(QtCore.QSize(0, 50))
        self.labelDescricaoPassos.setMaximumSize(QtCore.QSize(16777215, 50))
        self.labelDescricaoPassos.setText("")
        self.labelDescricaoPassos.setObjectName("labelDescricaoPassos")
        self.verticalLayout_3.addWidget(self.labelDescricaoPassos)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout.addWidget(self.frameSecaoProgresso)
        self.frame_SecaoCancelar = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.frame_SecaoCancelar.setFont(font)
        self.frame_SecaoCancelar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_SecaoCancelar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_SecaoCancelar.setObjectName("frame_SecaoCancelar")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_SecaoCancelar)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButtonCancelar = QtWidgets.QPushButton(self.frame_SecaoCancelar)
        self.pushButtonCancelar.setObjectName("pushButtonCancelar")
        self.horizontalLayout_3.addWidget(self.pushButtonCancelar)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.frame_SecaoCancelar)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindowExecucao.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindowExecucao)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindowExecucao.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindowExecucao)
        self.statusbar.setObjectName("statusbar")
        MainWindowExecucao.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowExecucao)
        QtCore.QMetaObject.connectSlotsByName(MainWindowExecucao)

    def retranslateUi(self, MainWindowExecucao):
        _translate = QtCore.QCoreApplication.translate
        MainWindowExecucao.setWindowTitle(_translate("MainWindowExecucao", "MainWindow"))
        self.pushButtonCancelar.setText(_translate("MainWindowExecucao", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindowExecucao = QtWidgets.QMainWindow()
    ui = Ui_MainWindowExecucao()
    ui.setupUi(MainWindowExecucao)
    MainWindowExecucao.show()
    sys.exit(app.exec_())
