# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\interfaceVisual\janelaAvaliacao.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_janelaAvaliacao(object):
    def setupUi(self, janelaAvaliacao):
        janelaAvaliacao.setObjectName("janelaAvaliacao")
        janelaAvaliacao.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(janelaAvaliacao)
        self.centralwidget.setObjectName("centralwidget")
        janelaAvaliacao.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(janelaAvaliacao)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        janelaAvaliacao.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(janelaAvaliacao)
        self.statusbar.setObjectName("statusbar")
        janelaAvaliacao.setStatusBar(self.statusbar)

        self.retranslateUi(janelaAvaliacao)
        QtCore.QMetaObject.connectSlotsByName(janelaAvaliacao)

    def retranslateUi(self, janelaAvaliacao):
        _translate = QtCore.QCoreApplication.translate
        janelaAvaliacao.setWindowTitle(_translate("janelaAvaliacao", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    janelaAvaliacao = QtWidgets.QMainWindow()
    ui = Ui_janelaAvaliacao()
    ui.setupUi(janelaAvaliacao)
    janelaAvaliacao.show()
    sys.exit(app.exec_())
