# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\interfaceVisual\janelaDetalhes.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowJanelaDetalhes(object):
    def setupUi(self, MainWindowJanelaDetalhes):
        MainWindowJanelaDetalhes.setObjectName("MainWindowJanelaDetalhes")
        MainWindowJanelaDetalhes.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindowJanelaDetalhes)
        self.centralwidget.setObjectName("centralwidget")
        MainWindowJanelaDetalhes.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindowJanelaDetalhes)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindowJanelaDetalhes.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindowJanelaDetalhes)
        self.statusbar.setObjectName("statusbar")
        MainWindowJanelaDetalhes.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowJanelaDetalhes)
        QtCore.QMetaObject.connectSlotsByName(MainWindowJanelaDetalhes)

    def retranslateUi(self, MainWindowJanelaDetalhes):
        _translate = QtCore.QCoreApplication.translate
        MainWindowJanelaDetalhes.setWindowTitle(_translate("MainWindowJanelaDetalhes", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindowJanelaDetalhes = QtWidgets.QMainWindow()
    ui = Ui_MainWindowJanelaDetalhes()
    ui.setupUi(MainWindowJanelaDetalhes)
    MainWindowJanelaDetalhes.show()
    sys.exit(app.exec_())
