# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\interfaceVisual\janelaExecucao.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_janelaExecucao(object):
    def setupUi(self, janelaExecucao):
        janelaExecucao.setObjectName("janelaExecucao")
        janelaExecucao.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(janelaExecucao)
        self.centralwidget.setObjectName("centralwidget")
        janelaExecucao.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(janelaExecucao)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        janelaExecucao.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(janelaExecucao)
        self.statusbar.setObjectName("statusbar")
        janelaExecucao.setStatusBar(self.statusbar)

        self.retranslateUi(janelaExecucao)
        QtCore.QMetaObject.connectSlotsByName(janelaExecucao)

    def retranslateUi(self, janelaExecucao):
        _translate = QtCore.QCoreApplication.translate
        janelaExecucao.setWindowTitle(_translate("janelaExecucao", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    janelaExecucao = QtWidgets.QMainWindow()
    ui = Ui_janelaExecucao()
    ui.setupUi(janelaExecucao)
    janelaExecucao.show()
    sys.exit(app.exec_())
