# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\interfaceVisual\janelaEdicao.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_janelaEdicao(object):
    def setupUi(self, janelaEdicao):
        janelaEdicao.setObjectName("janelaEdicao")
        janelaEdicao.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(janelaEdicao)
        self.centralwidget.setObjectName("centralwidget")
        janelaEdicao.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(janelaEdicao)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        janelaEdicao.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(janelaEdicao)
        self.statusbar.setObjectName("statusbar")
        janelaEdicao.setStatusBar(self.statusbar)

        self.retranslateUi(janelaEdicao)
        QtCore.QMetaObject.connectSlotsByName(janelaEdicao)

    def retranslateUi(self, janelaEdicao):
        _translate = QtCore.QCoreApplication.translate
        janelaEdicao.setWindowTitle(_translate("janelaEdicao", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    janelaEdicao = QtWidgets.QMainWindow()
    ui = Ui_janelaEdicao()
    ui.setupUi(janelaEdicao)
    janelaEdicao.show()
    sys.exit(app.exec_())
