# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\interfaceVisual\janelaAvaliacao.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowAvaliacao(object):
    def setupUi(self, MainWindowAvaliacao):
        MainWindowAvaliacao.setObjectName("MainWindowAvaliacao")
        MainWindowAvaliacao.resize(1000, 1000)
        MainWindowAvaliacao.setMinimumSize(QtCore.QSize(1000, 1000))
        self.centralwidget = QtWidgets.QWidget(MainWindowAvaliacao)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameTabela = QtWidgets.QFrame(self.centralwidget)
        self.frameTabela.setMinimumSize(QtCore.QSize(1000, 250))
        self.frameTabela.setMaximumSize(QtCore.QSize(16777215, 250))
        self.frameTabela.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTabela.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTabela.setObjectName("frameTabela")
        self.verticalLayout.addWidget(self.frameTabela)
        self.frame_grafico = QtWidgets.QFrame(self.centralwidget)
        self.frame_grafico.setMinimumSize(QtCore.QSize(1000, 800))
        self.frame_grafico.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_grafico.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grafico.setObjectName("frame_grafico")
        self.verticalLayout.addWidget(self.frame_grafico)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindowAvaliacao.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindowAvaliacao)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setObjectName("menubar")
        MainWindowAvaliacao.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindowAvaliacao)
        self.statusbar.setObjectName("statusbar")
        MainWindowAvaliacao.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowAvaliacao)
        QtCore.QMetaObject.connectSlotsByName(MainWindowAvaliacao)

    def retranslateUi(self, MainWindowAvaliacao):
        _translate = QtCore.QCoreApplication.translate
        MainWindowAvaliacao.setWindowTitle(_translate("MainWindowAvaliacao", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindowAvaliacao = QtWidgets.QMainWindow()
    ui = Ui_MainWindowAvaliacao()
    ui.setupUi(MainWindowAvaliacao)
    MainWindowAvaliacao.show()
    sys.exit(app.exec_())
